### ISSUE TITLE
Did not notify me about LO drop but did it for a AMN drop?

### ISSUE THREAD

**Issue by AnderssonPeter** [Kryszard-POD/Kryszard-s-PD2-Loot-Filter#1]
Love the loot filter but something is wonky when it notifies about AMN rune drops but not LO drops? also there is a %RED in the text guessing that is a bug? (I'm using a two or three day old version so both might be patched?)

![image](https://user-images.githubusercontent.com/1308309/99725622-b0e24c80-2ab5-11eb-953c-8bc7f93c692b.png)

**Comment by Kryszard-POD** [comment]
It doesn't look like my filter... So I can't help you, you have to switch
to my official filter :)

czw., 19 lis 2020, 22:22 użytkownik Peter <notifications@github.com>
napisał:

**Comment by AnderssonPeter** [comment]
Ok sorry i was confused updated now haven't verified that it solves the problem, hoping a IO drops again :P
