### ISSUE TITLE
Shophunting item notification

### ISSUE THREAD

**Issue by sanscriptum** [Kryszard-POD/Kryszard-s-PD2-Loot-Filter#12]
Hello, love the loot filter, but for some reason it fails to notify you about wands with lower resist charges, while staves with teleport are being marked no problem. Same with Venom/Shadow Disciplines claws The code seems to be correct though, so what gives?

**Comment by Kryszard-POD** [comment]
Yeah, it's bugged for some reason in this season, no idea why.

wt., 27 kwi 2021, 01:39 użytkownik sanscriptum ***@***.***>
napisał:
