### ISSUE TITLE
Hi~when update for S5?

### ISSUE THREAD

**Issue by weili0677** [Kryszard-POD/Kryszard-s-PD2-Loot-Filter#14]
Thank you for your work.
when update for S5？

**Comment by Kryszard-POD** [comment]
Hey,
I've got some IRL stuff on my head now, but I'll try to provide you filter ready for season 5 start :)

**Comment by weili0677** [comment]
> Hey, I've got some IRL stuff on my head now, but I'll try to provide you filter ready for season 5 start :)

Thank you so much. ^^
