### ISSUE TITLE
Season 6 Update

### ISSUE THREAD

**Issue by Gomzumi** [Kryszard-POD/Kryszard-s-PD2-Loot-Filter#16]
Hello.

Are you gonna update your filter when season 6 is ready?

**Comment by Kryszard-POD** [comment]
Yup, I am gonna do it 😉

wt., 8 lis 2022, 19:51 użytkownik zettimetti ***@***.***>
napisał:

**Comment by Gomzumi** [comment]
Sound great, best filter :D

**Comment by Gomzumi** [comment]
Thank you for the update :)

**Comment by Kryszard-POD** [comment]
You are welcome :) good luck&have fun

sob., 26 lis 2022, 23:43 użytkownik zettimetti ***@***.***>
napisał:
