### ISSUE TITLE
Season 7 Update

### ISSUE THREAD

**Issue by Gomzumi** [Kryszard-POD/Kryszard-s-PD2-Loot-Filter#17]
Hello.

Are you gonna update your filter when season 7 is ready?

**Comment by Kryszard-POD** [comment]
Yes sir, I will do my best to provide an update for upcoming season ;)

BR,

pon., 10 kwi 2023, 22:19 użytkownik zettimetti ***@***.***>
napisał:

**Comment by Gomzumi** [comment]
I appreciate it very much.

But i have a small naming request about all charms.

Here is a exemple like this:

Poisen & Bone Spells Skiller
Fungal Grand Charm

So it shows both names.

**Comment by Kryszard-POD** [comment]
Why do you need the oryginal name for?

wt., 11 kwi 2023, 13:35 użytkownik zettimetti ***@***.***>
napisał:

**Comment by Gomzumi** [comment]
It could be handy for players there trade or looking for specific charm.

In the same way as weapens, armors, shields etc.

**Comment by Gomzumi** [comment]
Thank you for the update :)

**Comment by Kryszard-POD** [comment]
You are welcome :)

pon., 1 maj 2023, 21:05 użytkownik zettimetti ***@***.***>
napisał:
