### ISSUE TITLE
Flawless/Perfect gems not notifying when they drop.

### ISSUE THREAD

**Issue by Polrond** [Kryszard-POD/Kryszard-s-PD2-Loot-Filter#2]
Hi, I wasn't sure were to say this, but I can't seem to get flawless/perfect gems to notify when they drop, have checked appropriate settings in game, and had a look through the loot filter but I am not sure what I am looking at. Any help would be appreciated. Thanks for your time.

**Comment by Kryszard-POD** [comment]
Perfect Gems will ping notify now, cause they can drop in Season II :)
