### ISSUE TITLE
Assassin specific claws missing

### ISSUE THREAD

**Issue by Marmeladenbrot** [Kryszard-POD/Kryszard-s-PD2-Loot-Filter#3]
Hi, in the Assassin Discord channel there is an additional bunch of item filters that are missing in all loot filters, including yours (https://discord.com/channels/701658302085595158/776859543141089330/819861766220939275).

Direct link to the additional filters: https://pastebin.com/Gb7CqnUh

Could you please add those filter rules to your loot filter? 😊

**Comment by Kryszard-POD** [comment]
Most of those are already in my filter, but I'll add more, don't worry :)

pt., 12 mar 2021, 13:19 użytkownik Vega ***@***.***> napisał:
