### ISSUE TITLE
item notification display

### ISSUE THREAD

**Issue by herbatadom** [Kryszard-POD/Kryszard-s-PD2-Loot-Filter#4]
My brother and I are both using this loot filter. He receives item notifications that are accurate. For example 'small charm' and 'plated belt' when they drop. I receive 'charm Small' and 'Girdle (h)' or 'plated boots'. I find these names confusing and annoying, since they are not the actual item name. But I don't know how to change it.

**Comment by Kryszard-POD** [comment]
That's becouse your in-game settings:
https://github.com/Kryszard-POD/Kryszard-s-PD2-Loot-Filter#in-game-settings

**Comment by herbatadom** [comment]
ok thankyou
