### ISSUE TITLE
Needless base lvl base restrictions - e.g. elite claw bases only visible at level 80+

### ISSUE THREAD

**Issue by Marmeladenbrot** [Kryszard-POD/Kryszard-s-PD2-Loot-Filter#5]
Problem:
1: Elite bases are restricted to min clvl 80

2: Needless char level limit <31
_//Class items
ItemDisplay[(SOR OR WAND OR SCEPTER OR STAFF OR DRU OR BAR OR NEC OR SIN) !INF NMAG **CLVL<31**]: %NAME% %GRAY%(%TAN%$%WHITE%%PRICE%%GRAY%)%CONTINUE%
ItemDisplay[(SOR OR WAND OR (wsp OR 9ws OR 7ws) OR (am5 OR ama OR amf) OR DRU OR BAR OR NEC OR SIN) (MAG OR RARE) !ID]: %NAME%_

Probably many more.

**Comment by Kryszard-POD** [comment]
You are wrong. You can see %CONTINUE% at the end of the line. Other lines
below catches those items and they are not hidden to lvl 80 for sure. You
can use FilterBird tool to test it :)

wt., 16 mar 2021, 12:28 użytkownik Vega ***@***.***> napisał:
