### ISSUE TITLE
How do I install this loot filter?

### ISSUE THREAD

**Issue by Endarire** [Kryszard-POD/Kryszard-s-PD2-Loot-Filter#6]
Greetings!

How do I install this filter?  I've never used any loot filter or similar code on PD2.  The below screenshot shows what I see when clicking on Project Diablo II's launcher button for loot filtration.

Thankee!

![image](https://user-images.githubusercontent.com/10439725/113660382-8ad6d680-9669-11eb-8858-54159e77fb35.png)

**Comment by Kryszard-POD** [comment]
You need to download and install new version of launcher first :)

wt., 6 kwi 2021, 06:49 użytkownik Endarire ***@***.***>
napisał:
