### ISSUE TITLE
Add exc/elite belts 

### ISSUE THREAD

**Issue by negesti** [Kryszard-POD/Kryszard-s-PD2-Loot-Filter#8]
exceptional and elite belt should be shown for crafting
I've copied the line for gloves for my local filter, not sure if there is a better/cleaner option

`    ItemDisplay[BELT ((EXC OR ELT) !(utg OR uhg)) MAG !ETH !ID]: %GRAY%* %BLUE%%NAME% %GRAY%*`

**Comment by Kryszard-POD** [comment]
Why, if you can simply buy or gamble for them?

wt., 13 kwi 2021, 19:49 użytkownik negesti ***@***.***>
napisał:

**Comment by negesti** [comment]
Kind of true. I checked A4 and A5 and could not by a single elite belt. Maybe that's my char level but they are not that common. 
NPC wont sell eth belts  either. 
Imho adding elite belts and include eths, should not add much clutter
` ItemDisplay[BELT ((ELT) !(utg OR uhg)) MAG !ID]: %GRAY%* %BLUE%%NAME% %GRAY%*`
