### ISSUE TITLE
4 Socketable Shields

### ISSUE THREAD

**Issue by 0xRenegade** [Kryszard-POD/Kryszard-s-PD2-Loot-Filter#9]
I see that 4 socket swords get marked as Larzuk socketable items, but shields don't seem to.

**Comment by Kryszard-POD** [comment]
Sorry I don't understand. What is the problem?

pon., 19 kwi 2021, 17:52 użytkownik 0xRenegade ***@***.***>
napisał:

**Comment by 0xRenegade** [comment]
I wrote shields instead of swords, my mistake! Swords are marked for 4 socket larzuk, but shields are not. An example would be Monarchs.

**Comment by Kryszard-POD** [comment]
Cause there is only three types of 4 socket shields in the game. Monarch,
Aegis and Ward. And only Monarch can be considered to use becouse of
strenght requirements

pon., 19 kwi 2021, 17:55 użytkownik 0xRenegade ***@***.***>
napisał:
